import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/page";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className='bg-[#0d0c22] text-white m-0 p-0'
      >
        <div className="flex flex-col justify-between border border-purple-500  m-auto px-5 min-h-[100vh]">
          <Navbar />
          {children}
          <Footer />
        </div>
        
      </body>
    </html>
  );
}
